# Generated by Django 5.2.7 on 2025-10-07 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_test"),
    ]

    operations = [
        migrations.DeleteModel(
            name="test",
        ),
    ]
